import Head from "next/head";
import { useState } from "react";
import Header from "./components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Iskren-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40"></main>
      <Header />
    </div>
  );
}
